export { handleSubmitClearance } from './submit-clearance'
export { handleRegisterResident } from './register-resident'
export { handleGetSubmissions, handlePatchSubmission } from './admin/submissions'
export { handleGetRegistrations, handlePatchRegistration } from './admin/registrations'
export { handleApproveRegistration } from './admin/approve-registration'
export { handleGenerateClearance } from './admin/generate-clearance'
export { handleGetFacilityBookings } from './admin/facility-bookings'
export { handleOAuthSetup } from './oauth/setup'
export { handleOAuthCallback } from './oauth/callback'
export { handleOAuthHealth } from './oauth/health'
