-- Seed data for Barangay Banadero
-- Update the NULL fields with your actual values after inserting

INSERT INTO barangays (
  slug,
  domain,
  is_active,
  name,
  full_name,
  city,
  province,
  phone,
  email,
  primary_color,
  tagline,
  mission,
  vision,
  google_client_id,
  google_client_secret,
  google_refresh_token,
  google_redirect_uri,
  google_drive_output_folder_id,
  google_drive_photo_folder_id,
  template_ids,
  philsms_api_token,
  philsms_notification_number,
  philsms_sender_id,
  officials,
  services,
  contacts,
  office_hours,
  projects,
  disclosure_links,
  google_form_urls,
  admin_password_hash,
  asset_bucket
) VALUES (
  'banadero',
  'banaderolegazpi.online',
  true,
  'Banadero',
  'Barangay Banadero',
  'Legazpi City',
  'Albay',
  NULL,
  NULL,
  '#1a5632',
  'Your tagline here',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '{
    "barangay": "",
    "residency": "",
    "good_moral": "",
    "indigency": "",
    "business": "",
    "facility": "",
    "blotter": "",
    "luntian": "",
    "cso_accreditation": "",
    "barangay_id": "",
    "cso_accreditation_page2": ""
  }'::jsonb,
  NULL,
  NULL,
  'PhilSMS',
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{}'::jsonb,
  NULL,
  'banadero-assets'
);
